try:
	lib_dict
except NameError:
	lib_dict = dict()

lib_dict['build-in'] = [
	{
		"type": "function",
		"name": "acos",
		"usage": """acos(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "argv",
		"usage": """argv(argnum [, argnum2])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "ascii",
		"usage": """ascii(integer-or-string)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "ascii",
		"usage": """ascii(integer-or-string)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "asin",
		"usage": """asin(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "atan",
		"usage": """atan(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "attribarray",
		"usage": """attribarray(s)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "bitmap",
		"usage": """bitmap(keyword, ...)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "browsefiles",
		"usage": """browsefiles(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "chdir",
		"usage": """chdir(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "close",
		"usage": """close(fifo)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "color",
		"usage": """color(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Colorfunc",
		"usage": """Colorfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "colormix",
		"usage": """colormix(n, r, g, b)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "coreleft",
		"usage": """coreleft(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "cos",
		"usage": """cos(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "currtime",
		"usage": """currtime()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "cut",
		"usage": """cut(phrase, type, ...)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "debug",
		"usage": """debug(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "error",
		"usage": """error(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Errorfunc",
		"usage": """Errorfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "exit",
		"usage": """exit(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Exitfunc",
		"usage": """Exitfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "exp",
		"usage": """exp(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "fifoctl",
		"usage": """fifoctl(fifo, cmd [, arg])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "fifosize",
		"usage": """fifosize(fifo)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "filetime",
		"usage": """filetime(cmd)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "finishoff",
		"usage": """finishoff()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "float",
		"usage": """float(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "flush",
		"usage": """flush(fifo)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "funkey",
		"usage": """funkey(function-key-num, function-to-call)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "garbcollect",
		"usage": """garbcollect()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "get",
		"usage": """get(fifo)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "integer",
		"usage": """integer(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Intrfunc",
		"usage": """Intrfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "kill",
		"usage": """kill(tid)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "limitsof",
		"usage": """limitsof(phrase)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "lock",
		"usage": """lock(name [, test])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "log",
		"usage": """log(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "log10",
		"usage": """log10(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "lsdir",
		"usage": """lsdir(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "mdep",
		"usage": """mdep(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("input", "close", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("input", "open", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("input", "isopen", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("input", "list/open/close/isopen", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("output", "close", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("output", "open", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("output", "isopen", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("output", "list/open/close/isopen", midi_port_number)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midi",
		"usage": """midi("portmap", "inport", chan, "outport")""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midibytes",
		"usage": """midibytes(byte1, byte2, byte3...)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "midifile",
		"usage": """midifile(filename)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "milliclock",
		"usage": """milliclock()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "mousewarp",
		"usage": """mousewarp(x, y)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "nargs",
		"usage": """nargs()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "nullfunc",
		"usage": """nullfunc(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "object",
		"usage": """object(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "objectinfo",
		"usage": """objectinfo(object, type)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "objectinfo",
		"usage": """objectinfo(object, type)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "objectlist",
		"usage": """objectlist()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "oldnargs",
		"usage": """oldnargs(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "oldtypeof",
		"usage": """oldtypeof(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "oldxy",
		"usage": """oldxy(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "onerror",
		"usage": """onerror(function)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "onexit",
		"usage": """onexit(function)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "open",
		"usage": """open(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "pathsearch",
		"usage": """pathsearch(file [, path])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "phdump",
		"usage": """phdump()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "phrase",
		"usage": """phrase(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "popup",
		"usage": """popup(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "pow",
		"usage": """pow(x, y)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "printf",
		"usage": """printf(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "priority",
		"usage": """priority(task, priority)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "prstack",
		"usage": """prstack()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "put",
		"usage": """put(fifo, data)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "rand",
		"usage": """rand(n1 [, n2])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "readphr",
		"usage": """readphr(fname)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "realtime",
		"usage": """realtime(phrase [, time [, repeat [, monitor] ] ])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "reboot",
		"usage": """reboot(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Rebootfunc",
		"usage": """Rebootfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "variable",
		"name": "Redrawfunc",
		"usage": """Redrawfunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "refunc",
		"usage": """refunc(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "rekeylib",
		"usage": """rekeylib(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "variable",
		"name": "Resizefunc",
		"usage": """Resizefunc = ?""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """Global variable""",
	},
	{
		"type": "function",
		"name": "screen",
		"usage": """screen(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "setmouse",
		"usage": """setmouse(type)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sin",
		"usage": """sin(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sizeof",
		"usage": """sizeof(anything)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sleeptill",
		"usage": """sleeptill(time)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "split",
		"usage": """split(phrase-or-string)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sprintf",
		"usage": """sprintf(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sqrt",
		"usage": """sqrt(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "string",
		"usage": """string(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "subbytes",
		"usage": """subbytes(MIDIBYTES-phrase, start, length)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "substr",
		"usage": """substr(string, start, length)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "symbolnamed",
		"usage": """symbolnamed(string)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "sync",
		"usage": """sync()""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "system",
		"usage": """system(cmd)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "tan",
		"usage": """tan(n)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "taskinfo",
		"usage": """taskinfo("list")""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "tempo",
		"usage": """tempo(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "typeof",
		"usage": """typeof(anything)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "unlock",
		"usage": """unlock(name)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "wait",
		"usage": """wait(tid)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "windobject",
		"usage": """windobject(objectid, [type])""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "windowobject",
		"usage": """windowobject(?)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
	{
		"type": "function",
		"name": "xy",
		"usage": """xy(x, y)""",
		"filename": "bltin.c",
		"fileline": -1,
		"desc": """""",
	},
]

